# Generated by Django 2.2 on 2019-04-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThingWithImage',
            new_name='Picture',
        ),
    ]
